# Generated by Django 4.1.2 on 2022-10-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('article', models.CharField(blank=True, max_length=20, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
